Tracker:AddLocations("locations/Devils Spine.json")
Tracker:AddLocations("locations/Fish.json")
Tracker:AddLocations("locations/Gale Cliffs.json")
Tracker:AddLocations("locations/Open Ocean.json")
Tracker:AddLocations("locations/Pale Reach.json")
Tracker:AddLocations("locations/Quest.json")
Tracker:AddLocations("locations/Research.json")
Tracker:AddLocations("locations/Stellar Basin.json")
Tracker:AddLocations("locations/The Marrows.json")
Tracker:AddLocations("locations/Tool.json")
Tracker:AddLocations("locations/Twisted Strand.json")
Tracker:AddLocations("locations/Overworld.json")
